### ISSUE TITLE
Problem use module

### ISSUE THREAD

**Issue by ferrymiddelkoop** [humhub/humhub-modules-translation#24]
I have install this module en that go fine. I see in the topbar translation en when i click a get the follow error.

```
An Error occurred while handling another error:
exception 'yii\web\HeadersAlreadySentException' with message 'Headers already sent in /volume1/web/protected/modules/translation/messages/am/._base.php on line 1.' in /volume1/web/protected/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /volume1/web/protected/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /volume1/web/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /volume1/web/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\ErrorException))
#4 {main}
Previous exception:
exception 'yii\base\ErrorException' with message 'array_filter() expects parameter 1 to be array, integer given' in /volume1/web/protected/modules/translation/Module.php:39
Stack trace:
#0 /volume1/web/protected/modules/translation/controllers/TranslateController.php(191): humhub\modules\translation\Module->getModulePercentage()
#1 /volume1/web/protected/modules/translation/controllers/TranslateController.php(192): humhub\modules\translation\controllers\TranslateController->humhub\modules\translation\controllers\{closure}()
#2 /volume1/web/protected/modules/translation/controllers/TranslateController.php(192): ::array_walk()
#3 /volume1/web/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): humhub\modules\translation\controllers\TranslateController->actionIndex()
#4 /volume1/web/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/volume1/web/protected/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#5 /volume1/web/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#6 /volume1/web/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction()
#7 /volume1/web/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#8 /volume1/web/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest()
#9 /volume1/web/index.php(25): yii\base\Application->run()
#10 {main}
```

**Comment by buddh4** [comment]
I'd not suggest using this module for overwriting your own translations since changes probably will be overwritten when updating your installation. Currently the recommended way of overwriting translations is [by configuration](http://docs.humhub.org/admin-translations.html#overwrite-translation-messages).

In case you want to contribute to the official translation, please have a look [at the translation community](https://translate.humhub.org/dashboard)
